controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

about_us:
  path:
    pl: /{_locale}/o-nas
    en: /{_locale}/about-us
    nl: /{_locale}/over-ons
  controller: App\Controller\HomeController::about
  methods: GET|HEAD
