controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

app_about_us:
  path:
    pl: /{_locale}/o-nas
    en: /{_locale}/about-us
    de: /{_locale}/uber-uns
  controller: App\Controller\HomeController::about
  methods: GET|HEAD
